contexts:
- data:
    output_dir: app-interface-processed
    services_dir: app-interface-services
    templates_dir: app-interface-templates
  name: app-interface
- data:
    output_dir: visual-qontract-processed
    services_dir: visual-qontract-services
    templates_dir: visual-qontract-templates
  name: visual-qontract
- data:
    output_dir: qontract-reconcile-processed
    services_dir: qontract-reconcile-services
    templates_dir: qontract-reconcile-templates
  name: qontract-reconcile
current: app-interface
